create table state (
  st_id bigint generated by default as identity(start with 100, increment by 1) primary key,
  st_code varchar(50) unique not null,
  st_title varchar(255) not null
);

create table location (
  lc_id bigint generated by default as identity(start with 100, increment by 1) primary key,
  lc_x bigint not null,
  lc_y bigint not null
);

create table snapshot (
  sn_id bigint generated by default as identity(start with 100, increment by 1) primary key,
  sn_last_turn_id bigint,
  sn_dump varchar(9),
  foreign key (sn_last_turn_id) references location (lc_id)
);

create table game (
  gm_id bigint generated by default as identity(start with 100, increment by 1) primary key,
  gm_state_id bigint not null,
  gm_title varchar(255) not null,
  gm_snapshot_id bigint not null,
  foreign key (gm_state_id) references state (st_id),
  foreign key (gm_snapshot_id) references snapshot (sn_id)
);
